name: Build on PR

on:
  pull_request:
    types:
      - opened

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
