name: Build on PR

on:
  pull_request:
    types:
      - opened

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

  cr-movement:
    name: "CR Movement"
    uses: rishi-external/qcom-reusable-workflows/.github/workflows/qswat/reusable-pr-to-workflow-dependency.yml@main
    with:
      workflow_id: ${{ github.run_id }}
      run_attempt: ${{ github.run_attempt }}
      pr_number: ${{ github.event.pull_request.number }}
